services:
  db:
    image: mysql:9.2.0
    restart: always
    environment:
      MYSQL_DATABASE: patient_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql+asyncmy://user:password@db:3306/patient_db
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_PORT=2525
      - EMAIL_USER=eb23e02d772440
      - EMAIL_PASSWORD=278e526e98fee1
    volumes:
      - ./app:/app

volumes:
  mysql_data:
