"""Create patients table

Revision ID: 8b72276e6388
Revises: 
Create Date: 2025-03-01 15:19:59.621899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b72276e6388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('document_photo', sa.LargeBinary(), nullable=False),
    sa.Column('document_photo_filename', sa.String(length=255), nullable=False),
    sa.Column('document_photo_content_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patients_email_unique', 'patients', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_patients_email_unique', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
