"""Change document_photo to MEDIUMBLOB

Revision ID: b2faf5a283cc
Revises: 8b72276e6388
Create Date: 2025-03-01 18:53:45.563085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2faf5a283cc'
down_revision = '8b72276e6388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'document_photo',
               existing_type=sa.BLOB(),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)
    op.alter_column('patients', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('patients', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('patients', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('patients', 'document_photo',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.BLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
